### ISSUE TITLE
add more test cases for ShoppingListItem .render() 

### ISSUE THREAD

**Issue by theRemix** [edsperanto/devleague--behavior-driven-shopping-list#14]
add more test specs when the user

- create a new ShoppingListItem, set `is_done` to true, assert the desired output from `render()` is what you expect
- create a new ShoppingListItem, set `is_done` to true, set `is_done` to false, assert the desired output from `render()` is what you expect

around : https://github.com/edsperanto/devleague--behavior-driven-shopping-list/blob/master/js/shopping_list_item_test.js#L44

**Comment by ed-scaped** [comment]
fixed

**Comment by theRemix** [comment]
@edsperanto which commit fixes this?

i still see just one spec that asserts one case.
the issue asks for more (additional) specs

**Comment by ed-scaped** [comment]
sorry forgot to git push, just pushed my repo

**Comment by theRemix** [comment]
actually, the `it()` blocks have been re-used.
it is better practice to have each `it()` test just one thing, then add more `it()` (specs) for additional cases.
refactor this so that checking if myItem.is_done is false, and checking the output of .render()ing after setting is_done is what you expect, separately. 
the key here is isolation. if a test fails, you'd want to report which single error caused the failure.
