### ISSUE TITLE
"hard" assert ShoppingListItem .render()

### ISSUE THREAD

**Issue by theRemix** [edsperanto/devleague--behavior-driven-shopping-list#15]
using dynamic values here could be problematic. what if `myItem.is_done` is `null` instead of the expected `true` or `false` values.
the `render()` method would return `<li class='completed_null' ...` and the tests will still pass, while this is not actually the desired behavior. 

you should expect the li class to be `'completed_false'`

(if it says anything except `'completed_false'` make this spec fail)

at line : https://github.com/edsperanto/devleague--behavior-driven-shopping-list/blob/master/js/shopping_list_item_test.js#L42

**Comment by ed-scaped** [comment]
fixed

**Comment by theRemix** [comment]
which commit fixes this?
i still see dynamic values in the `.render()` spec

**Comment by theRemix** [comment]
✅ lgtm 

for future reference, on the commit that fixes this issue, in the commit message use https://help.github.com/articles/closing-issues-via-commit-messages/

```
[your normal commit message]

resolves #15
```
